from kivy_resource.AboutScreen.about_screen import AboutScreen
from kivy_resource.LoginScreen.login_screen import LoginScreen
from kivy_resource.ResourceEditScreen.resource_edit_screen import ResourceEdit
from kivy_resource.ResourceListScreen.resource_list_screen import Resource
from kivy_resource.ResourceListScreen.resource_list_screen import ResourceList
