from kivy_resource.AboutScreen.about_screen import AboutScreen
from kivy_resource.LoginScreen.login_screen import LoginScreen
from kivy_resource.BookEditScreen.book_edit_screen import BookEdit
from kivy_resource.BookListScreen.book_list_screen import Book
from kivy_resource.BookListScreen.book_list_screen import BookList
